Kyungcheolkoh/install and configuration
DrawDream-incorporated/Project-Zeus-FE pull request #34
Opened 2024-01-28 05:00 UTC by kckoh

- configuration and installation
- installed libraries: storybook, eslint, prettier, react test library
- an example test case for app

2024-01-29 13:08 UTC, bl216 approved these changes

2024-01-30 05:23 UTC, HanKyungSung requested changes

2024-01-30 05:23 UTC, HanKyungSung commented on .eslintrc.js
Can you apply eslint only under src directory? It seems it applies to other files that need not be checked.  For instance, `ISSUE_TEMPLATE` does not need to be checked.

2024-02-02 04:18 UTC, kckoh commented on .eslintrc.js
This was part of the prettier formating not the eslint. I set the prettier to only work under the src. Please take a look at the package.json file.

2024-02-04 01:21 UTC, HanKyungSung approved these changes

2024-02-04 21:38 UTC, merged